on:
  push:
    branches:
      - main

name: 🚀 Deploy website via FTP

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#skipGA') }}

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        # dry-run: true
        server: ftpupload.net
        port: 21
        protocol: ftps
        username: if0_38156084
        password: ${{ secrets.ftp_password }}
        server-dir: /solowebworks.com/htdocs/wfl/
        exclude: |
          **/.git*
          **/.git*/**
          **/.vscode
          **/.vscode/**
          **/database/**
          README.md
